# Generated by Django 4.1.7 on 2023-02-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(blank=True, null=True)),
                ('post', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=64, null=True)),
                ('responsibility', models.TextField(blank=True, db_collation='utf8mb3_general_ci', null=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='First_Name', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Last_Name', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=20, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypesLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpls_id', models.IntegerField(blank=True, null=True)),
                ('type_lesson', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=255, null=True)),
                ('long', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=255, null=True)),
            ],
            options={
                'db_table': 'types_lessons',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
